### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by SaltSouls** [Goldenrevolver/ValheimSpearModsAndFriends#1] opened 2023-10-21 21:49 UTC
I'm asking this here since I don't seem to be able to find it anywhere on your mod page, but are these changes to only the vanilla weapons, or do they work with modded ones, like the ones from warfare, as well? If they don't, it would be great if we could get some compatibility between the two as these look like they would make spears far more useful than they currently are.

**Comment by Goldenrevolver** [comment] 2023-10-22 02:37
here or on nexusmods is the right place for this. please next time specify which mod you are referring to since this repository contains all my spear mods

I assuming you mean proper spears. my mod affects every weapon that has the skill type "spear" (so its damage scales with the spear skill) and its primary attack is the default overhead 'spear poke' attack. so it affect every modded spear that my mod should change in the first place. it should affect warfare spears, but not warfare warpikes, also as intended. but I haven't actually installed warfare to test that. if there is an issue with any modded spear, you can always let me know.

**Comment by Goldenrevolver** [comment] 2023-10-22 05:13
I'll add it to the mod page in the next update and close this issue as done

**Closed as completed by Goldenrevolver** 2023-10-22 05:13 UTC
